units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 5
  py: ky + 5
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      columns:
        inner.key:
        pointer.key:
        middle.key:
            stagger: 11
        ring.key:
            stagger: -5
        pinky.key:
            stagger: -9
        outer.key:
      rows:
        bottom:
        center:
        top:
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-28, -25]
      columns:
        left.key:
          stagger: -15
          height: 1.5kx
        middle.key:
          stagger: 5
          height: 1.5kx
        right.key:
          stagger: 5
          height: 1.5kx
      rotate: 3 #was 5 pre spread
outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      fillet: 7
      expand: 3
      joints: 0
      points:
        - ref: thumb_left
          shift: [-0.5px,0.5py]
        - ref: thumb_left
          shift: [-0.5px,-0.75ky -5]
        - ref: thumb_right
          shift: [0.5px,-0.75ky -5]
        - ref: thumb_right
          shift: [0.5px, 0.25py]
        - ref: matrix_outer_bottom
          shift: [0.55px,-0.55py]
        - ref: matrix_outer_top
          shift: [.75px,0.5py]
        - ref: matrix_middle_top
          shift: [.75px,0.5py]
        - ref: matrix_middle_top
          shift: [-1px,0.5py]
        - ref: matrix_inner_top
          shift: [-1.25px,1py]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  pcbboard:
    outlines:
      matrix:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: GND
          to: "{{name}}"
      choc_soldier:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          from: GND
          to: "{{name}}"
      mountinghole0:
        what: mountinghole
        where:
          ref: thumb_left
          shift: [-10, -16]
      mountinghole1:
        what: mountinghole
        where:
          ref: thumb_right
          shift: [10, -16]
      mountinghole2:
        what: mountinghole
        where:
          ref: matrix_outer_bottom
          shift: [12, -11]
      mountinghole3:
        what: mountinghole
        where:
          ref: matrix_outer_top
          shift: [16, 10]
      mountinghole4:
        what: mountinghole
        where:
          ref: matrix_inner_top
          shift: [-28, 22]
      trrs:
        what: trrs
        where:
          ref: matrix_inner_bottom
          rotate: 90
          shift: [-35, -5]
        params:
          A: GND
          B: GND
          C: D1
          D: VCC
          reverse: true
          symmetric: true
      promicro:
        what: pi_pico_left
        params:
          orientation: "down"
          D0: thumb_left
          D4: thumb_middle            
          C6: thumb_right             
          D7: matrix_outer_bottom     
          E6: matrix_pinky_bottom
          B4: matrix_ring_bottom     
          B5: matrix_middle_bottom   
          B7: matrix_pointer_bottom  
          D5: matrix_inner_bottom    
          C7: matrix_outer_center    
          F1: matrix_pinky_center
          F0: matrix_ring_center
          B6: matrix_middle_center
          B2: matrix_pointer_center
          B3: matrix_inner_center
          B1: matrix_outer_top
          F7: matrix_pinky_top
          F6: matrix_ring_top
          F5: matrix_middle_top
          F4: matrix_pointer_top
          B0: matrix_inner_top
        where:
          ref: matrix_inner_center
          shift: [-21,0]
          rotate: -90
