units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 5
  py: ky + 5
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      columns:
        inner.key:
        pointer.key:
        middle.key:
            stagger: 11
        ring.key:
            stagger: -5
        pinky.key:
            stagger: -9
        outer.key:
      rows:
        bottom:
        center:
        top:
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-28, -20]
      columns:
        left.key:
          stagger: -15
        middle.key:
          stagger: 5
        right.key:
          stagger: 5
      rotate: 5
outlines:
  # comment for prod
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: outline
      name: keys
      fillet: 1
      expand: 7
    - what: rectangle
      size: [50, 55]
      corner: 6
      where:
        ref: matrix_inner_bottom
        shift: [-14, 1.5]
        rotate: 5
  # comment for prod
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  pcbboard:
    outlines:
      matrix:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{name}}"
          to: GND
      trrs: 
        what: trrs
        params:
          reverse: true
          A: B5 # Bad pin placement should be at end
          B: B7 # Bad pin placement should be at end
          C: GND
          D: VCC
        where: 
          ref: matrix_inner_bottom
          shift: [-33, -18]
          rotate: 95
      bottom_left_mount:
        what: mountinghole
        where:
          ref: thumb_left
          shift: [-11, -11]
      bottom_middle_mount:
        what: mountinghole
        where:
          ref: matrix_ring_bottom
          shift: [-11, -11]
      bottom_middle_right_mount:
        what: mountinghole
        where:
          ref: thumb_right
          shift: [11, -11]
      bottom_right_mount:
        what: mountinghole
        where:
          ref: matrix_outer_bottom
          shift: [11, -11]
      top_right_mount:
        what: mountinghole
        where:
          ref: matrix_outer_top
          shift: [11, 11]
      top_middle_moount:
        what: mountinghole
        where:
          ref: matrix_middle_top
          shift: [0, 12]
      top_left_mount:
        what: mountinghole
        where:
          ref: matrix_inner_top
          shift: [-11, 11]
      between_thumb_pcb_mount:
        what: mountinghole
        where:
          ref: matrix_inner_bottom
          shift: [-3, -14]
      left_center_mount:
        what: mountinghole
        where:
          ref: matrix_inner_center
          shift: [-37, 6]
      rp2024_elite:
        what: elite
        params:
          # GND:
          # VCC:used for trrs
          # ST: 
          D3: thumb_right
          D2: thumb_middle 
          D1: thumb_left
          D0: matrix_outer_bottom
          D4: matrix_pinky_bottom
          C6: matrix_ring_bottom
          D7: matrix_middle_bottom
          E6: matrix_pointer_bottom
          B4: matrix_inner_bottom
          # B5: used for trrs
          # B7: used for trrs 
          D5: matrix_outer_center
          C7: matrix_pinky_center
          F1: matrix_ring_center
          F0: matrix_middle_center
          B6: matrix_pointer_center
          B2: matrix_inner_center
          B3: matrix_outer_top
          B1: matrix_pinky_top 
          F7: matrix_ring_top
          F6: matrix_middle_top
          F5: matrix_pointer_top
          F4: matrix_inner_top
          # B0: not used
        where:
          ref: matrix_inner_bottom
          shift: [-24,6]
          rotate: -85
