units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 5
  py: ky + 5
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      columns:
        inner.key:
        pointer.key:
        middle.key:
            stagger: 11
        ring.key:
            stagger: -5
        pinky.key:
            stagger: -9
        outer.key:
      rows:
        bottom:
        center:
        top:
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-28, -20]
      columns:
        left.key:
          stagger: -15
        middle.key:
          stagger: 5
        right.key:
          stagger: 5
      rotate: 5
outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: outline
      name: keys
      fillet: 1
      expand: 6
    - what: rectangle
      size: [50, 55]
      corner: 5
      where:
        ref: matrix_inner_bottom
        shift: [-13, 0]
        rotate: 5
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  pcbboard:
    outlines:
      matrix:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: GND
          to: "{{name}}"
      choc_soldier:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          from: GND
          to: "{{name}}"
      jstph: 
        what: jstph
        params:
          pos: VCC
          neg: GND
        where: 
          ref: matrix_inner_bottom
          shift: [-30, -15]
          rotate: 95
      promicro:
        what: promicro
        params:
          # RAW:
          # GND:
          # RST:
          # VCC:
          P21: thumb_left
          P20: thumb_middle
          P19: thumb_right
          P18: matrix_outer_bottom
          P15: matrix_ring_bottom
          P14: matrix_middle_bottom
          P16: matrix_pointer_bottom
          P10: matrix_inner_bottom
          P1:  matrix_outer_middle
          P0:  matrix_ring_middle
          P2:  matrix_middle_middle
          P3:  matrix_pointer_middle
          P4:  matrix_inner_middle
          P5:  matrix_outer_top
          P6:  matrix_ring_top
          P7:  matrix_middle_top
          P9:  matrix_inner_top
          P8:  matrix_pointer_top
        where:
          ref: matrix_inner_bottom
          shift: [-24,5]
          rotate: -85
